"""Weishaupt protocol enums."""

from enum import IntEnum


class SysError(IntEnum):
    """System error and warning codes."""

    NO_ERROR = 65535

    REFRIGERANT_SENSOR_EXPANSION_INLET = 1
    INTAKE_AIR_SENSOR = 2
    HEAT_EXCHANGER_SENSOR = 3
    COMPRESSOR_SUCTION_GAS_SENSOR = 4
    EVI_SUCTION_GAS_SENSOR = 5
    REFRIGERANT_SENSOR_INLET_OUTLET = 6
    OIL_SUMP_SENSOR = 7
    EVI_EXPANSION_VALVE = 8
    LOW_PRESSURE_SENSOR = 9
    HIGH_PRESSURE_SENSOR = 10
    MEDIUM_PRESSURE_SENSOR = 11
    COOLING_EXPANSION_VALVE = 12
    INVERTER_COMMUNICATION = 13
    OUTDOOR_UNIT_COMMUNICATION = 14
    HIGH_PRESSURE_SWITCH = 15
    INVERTER_LOCKED = 16
    EEPROM_MEMORY_ERROR = 17
    CONTROLLER_MODBUS_COMMUNICATION = 18
    INVERTER_ALARM = 19
    COMPRESSOR_CONFIGURATION = 20
    LOW_PRESSURE_FAULT = 21
    LOW_SUPERHEAT = 22
    HIGH_SUPERHEAT = 23
    EVI_HIGH_SUPERHEAT = 24
    LOW_REFRIGERANT = 25
    HIGH_PRESSURE_FAULT = 26
    LOW_CONDENSATION_TEMPERATURE = 27
    HIGH_CONDENSATION_TEMPERATURE = 28
    LOW_EVAPORATION_TEMPERATURE = 29
    HIGH_EVAPORATION_TEMPERATURE = 30
    HEAT_PUMP_INCOMPATIBLE = 32
    CONTROLLER_EXTENSION_MODULE_COMMUNICATION = 33
    LOW_FLOW = 40
    NEGATIVE_SPREAD = 41
    FAN_BLOCKED = 43
    FAN_SPEED_LOW = 44
    CONTROLLER_REFRIGERATION_COMMUNICATION = 47
    OUTDOOR_SENSOR_INTERRUPTED = 50
    OUTDOOR_SENSOR_SHORT_CIRCUIT = 51
    DIVERTING_VALVE_SENSOR_INTERRUPTED = 52
    DIVERTING_VALVE_SENSOR_SHORT_CIRCUIT = 53
    HOT_WATER_SENSOR_INTERRUPTED = 54
    HOT_WATER_SENSOR_SHORT_CIRCUIT = 55
    CONDENSER_FLOW_SENSOR_INTERRUPTED = 56
    CONDENSER_FLOW_SENSOR_SHORT_CIRCUIT = 57
    FLOW_SENSOR_INTERRUPTED = 58
    FLOW_SENSOR_SHORT_CIRCUIT = 59
    RETURN_SENSOR_INTERRUPTED = 60
    RETURN_SENSOR_SHORT_CIRCUIT = 61
    BUFFER_SENSOR_INTERRUPTED = 64
    BUFFER_SENSOR_SHORT_CIRCUIT = 65
    REGENERATIVE_MIXER_SENSOR_INTERRUPTED = 66
    REGENERATIVE_MIXER_SENSOR_SHORT_CIRCUIT = 67
    SECOND_HEATING_CIRCUIT_SENSOR_INTERRUPTED = 70
    SECOND_HEATING_CIRCUIT_SENSOR_SHORT_CIRCUIT = 71
    SENSOR_T1_2_INTERRUPTED = 72
    SENSOR_T1_2_SHORT_CIRCUIT = 73
    SENSOR_T2_2_INTERRUPTED = 74
    SENSOR_T2_2_SHORT_CIRCUIT = 75
    ANALOG_INPUT_AE1_INTERRUPTED = 90
    ANALOG_INPUT_AE1_SHORT_CIRCUIT = 91
    ANALOG_INPUT_AE2_INTERRUPTED = 92
    ANALOG_INPUT_AE2_SHORT_CIRCUIT = 93
    ANALOG_INPUT_AE3_INTERRUPTED = 94
    ANALOG_INPUT_AE3_SHORT_CIRCUIT = 95
    OUTSIDE_OPERATING_LIMITS = 101
    DEFROST_TIME_EXCEEDED = 102
    REFRIGERATION_CIRCUIT_COMMUNICATION = 103
    DISCHARGE_GAS_TEMPERATURE_HIGH = 104
    INVERTER_CURRENT_HIGH = 105
    CURRENT_CONSUMPTION_HIGH = 106
    INVERTER_DC_VOLTAGE_HIGH = 107
    INVERTER_DC_VOLTAGE_LOW = 108
    VOLTAGE_OUTSIDE_RANGE_LOW = 109
    VOLTAGE_OUTSIDE_RANGE_HIGH = 110
    HIGH_PRESSURE_SWITCH_2 = 111
    INVERTER_OVERHEATED = 112
    INVERTER_OVERHEATED_2 = 113
    COMPRESSOR_POSITION_UNDETERMINED = 114
    INVERTER_DC_VOLTAGE_LOW_2 = 117
    COMPRESSOR_INVERTER_CURRENT_HIGH = 118
    COMPRESSOR_CURRENT_TIMEOUT = 119
    INVERTER_TEMPERATURE_HIGH = 120
    INVERTER_VOLTAGE_LOW = 121
    MODBUS_CONFIGURATION_ERROR = 122
    MODBUS_CONNECTION = 123
    DISCHARGE_GAS_TEMPERATURE_HIGH_2 = 124
    INVERTER_TEMPERATURE_HIGH_2 = 127
    INVERTER_OVERHEATED_3 = 128
    MODBUS_COMMUNICATION_ERROR = 129
    MODBUS_COMMUNICATION_ERROR_2 = 130
    ELECTRONICS_ERROR = 133
    HIGH_PRESSURE_SWITCH_DEFECTIVE = 135
    COMPRESSOR_CONFIGURATION_2 = 136
    HIGH_PRESSURE_SWITCH_CONFIGURATION = 137
    DISCHARGE_GAS_TEMPERATURE_LOW = 140
    INVERTER_TEMPERATURE_LOW = 143
    CHOKE_TEMPERATURE_LOW = 144
    COMPRESSOR_CURRENT_SENSOR_PHASE_U = 150
    COMPRESSOR_CURRENT_SENSOR_PHASE_V = 151
    COMPRESSOR_CURRENT_SENSOR_PHASE_W = 152
    CURRENT_SENSOR_ERROR = 153
    INVERTER_TEMPERATURE_SENSOR_ERROR = 154
    TEMPERATURE_SENSOR_ERROR = 155
    DISCHARGE_GAS_SENSOR_ERROR = 156
    REFRIGERATION_CONTROLLER_COMMUNICATION = 157
    EEPROM_MEMORY_ERROR_2 = 158
    CURRENT_CONSUMPTION_HIGH_2 = 159
    VOLTAGE_OUTSIDE_RANGE_2 = 160
    VOLTAGE_OUTSIDE_RANGE_3 = 161
    INVERTER_DC_VOLTAGE_HIGH_2 = 162
    INVERTER_DC_VOLTAGE_LOW_3 = 163
    HIGH_PRESSURE_SWITCH_3 = 164
    COMPRESSOR_PHASE_INTERRUPTED = 165
    INVERTER_OVERHEATED_4 = 166
    INVERTER_OVERHEATED_5 = 167
    COMPRESSOR_CONFIGURATION_ERROR = 168
    COMPRESSOR_CURRENT_HIGH = 169
    COMPRESSOR_PHASE_U_OVERVOLTAGE = 170
    COMPRESSOR_PHASE_V_OVERVOLTAGE = 171
    COMPRESSOR_PHASE_W_OVERVOLTAGE = 172
    COMPRESSOR_PHASE_FAILURE = 173
    COMPRESSOR_BLOCKED = 174
    COMPRESSOR_START_FAILURE = 175
    IRREGULAR_INVERTER_VOLTAGE = 176
    COMPRESSOR_OVERLOADED = 177
    DISCHARGE_GAS_TEMPERATURE_HIGH_3 = 178
    INVERTER_TEMPERATURE = 179
    COMPRESSOR_BLOCKED_2 = 180
    COMPRESSOR_BLOCKED_3 = 181
    CURRENT_CONSUMPTION_HIGH_3 = 182
    CURRENT_CONSUMPTION_HIGH_4 = 183
    VOLTAGE_HIGH = 184


class SysOperatingDisplay(IntEnum):
    """System operating display values (register 30006)."""

    UNDEFINED = 0
    RELAY_TEST = 1
    EMERGENCY_STOP = 2
    DIAGNOSIS = 3
    MANUAL = 4
    MANUAL_HEATING = 5
    MANUAL_COOLING = 6
    MANUAL_DEFROST = 7
    DEFROST = 8
    SECOND_HEAT_SOURCE = 9
    EVU_LOCK = 10
    SG_TARIFF = 11
    SG_MAXIMUM = 12
    TARIFF_LOAD = 13
    ELEVATED_OPERATION = 14
    STANDBY_TIME = 15
    STANDBY = 16
    RINSE = 17
    FROST_PROTECTION = 18
    HEATING = 19
    HOT_WATER = 20
    LEGIONELLA_PROTECTION = 21
    SWITCH_HEATING_COOLING = 22
    COOLING = 23
    PASSIVE_COOLING = 24
    SUMMER = 25
    SWIMMING_POOL = 26
    VACATION = 27
    SCREED_PROGRAM = 28
    LOCKED = 29
    LOCKED_OUTDOOR_TEMPERATURE = 30
    LOCKED_SUMMER = 31
    LOCKED_WINTER = 32
    APPLICATION_LIMIT = 33
    HEATING_CIRCUIT_LOCK = 34
    LOWERING = 35
    REGENERATIVE_FLOW = 36
    HEATING_SGR = 37
    HOT_WATER_SGR = 39
    OIL_RECIRCULATION = 43


class SysOperatingMode(IntEnum):
    """System operating mode values (register 40001)."""

    AUTOMATIC = 0
    HEATING = 1
    COOLING = 2
    SUMMER = 3
    STANDBY = 4
    SECOND_HEAT_SOURCE = 5


class HeatPumpOperation(IntEnum):
    """System operating mode values (register 40001)."""

    UNDEFINED = 0
    RELAY_TEST = 1
    EMERGENCY_STOP = 2
    DIAGNOSIS = 3
    MANUAL = 4
    MANUAL_HEATING = 5
    MANUAL_COOLING = 6
    MANUAL_DEFROST = 7
    DEFROST = 8
    SECOND_HEAT_SOURCE = 9
    EVU_LOCK = 10
    SG_TARIFF = 11
    SG_MAXIMUM = 12
    TARIFF_LOAD = 13
    ELEVATED_OPERATION = 14
    STANDBY_TIME = 15
    STANDBY = 16
    RINSE = 17
    FROST_PROTECTION = 18
    HEATING = 19
    HOT_WATER = 20
    LEGIONELLA_PROTECTION = 21
    SWITCH_HEATING_COOLING = 22
    COOLING = 23
    PASSIVE_COOLING = 24
    SUMMER = 25
    SWIMMING_POOL = 26
    VACATION = 27
    SCREED_PROGRAM = 28
    LOCKED = 29
    LOCKED_OUTDOOR_TEMPERATURE = 30
    LOCKED_SUMMER = 31
    LOCKED_WINTER = 32
    APPLICATION_LIMIT = 33
    HEATING_CIRCUIT_LOCK = 34
    LOWERING = 35
    READINESS = 36
    HEATING_SGR = 37
    HOT_WATER_SGR = 39
    OIL_RECIRCULATION = 43


class HeatPumpFault(IntEnum):
    """Heat pump fault status values (register 33102)."""

    FAULT = 0
    NO_FAULT = 1


class HeatPumpConfiguration(IntEnum):
    """Heat pump configuration values (register 43101)."""

    NOT_CONFIGURED = 0
    HEATING = 1
    HEATING_COOLING = 2
    HEATING_COOLING_3 = 3
    HEATING_HOT_WATER = 4


class HeatPumpRestMode(IntEnum):
    """Heat pump rest mode values (register 43102)."""

    OFF = 0
    LIMIT_80_PERCENT = 1
    LIMIT_60_PERCENT = 2
    LIMIT_40_PERCENT = 3


class HeatingCircuitConfiguration(IntEnum):
    """Heating circuit configuration."""

    OFF = 0
    PUMP_CIRCUIT = 1
    MIXING_CIRCUIT = 2
    PUMP_SETPOINT = 3


class HeatingCircuitDemand(IntEnum):
    """Heating circuit demand mode."""

    OFF = 0
    WEATHER_CONTROLLED = 1
    ROOM_CONTROLLED = 2
    CONSTANT = 3


class HeatingCircuitOperation(IntEnum):
    """Heating circuit operation mode."""

    AUTOMATIC = 0
    COMFORT = 1
    NORMAL = 2
    LOWERING = 3
    STANDBY = 4


class SecondHeatSourceStatus(IntEnum):
    """Second heat source status."""

    OFF = 0
    ON = 1


class SecondHeatSourceConfiguration(IntEnum):
    """Second heat source configuration."""

    CONFIGURATION_0 = 0
    CONFIGURATION_1 = 1
    CONFIGURATION255 = 255


class ElectricHeater1Configuration(IntEnum):
    """Electric heater 1 configuration."""

    ENABLED = 5
    OFF = 255


class ElectricHeater2Configuration(IntEnum):
    """Electric heater 2 configuration."""

    ENABLED = 6
    OFF = 255
