from .description import WebifSensorDescription
from .params import (
    PARAMS_ENERGY,
    PARAMS_FLOW_RATE,
    PARAMS_HOURS,
    PARAMS_KELVIN,
    PARAMS_PERCENTAGE,
    PARAMS_POWER,
    PARAMS_PRESSURE,
    PARAMS_RPM,
    PARAMS_TEMPERATURE,
    PARAMS_TEXT,
)

WEBIF_HEAT_PUMP: list[WebifSensorDescription] = [
    WebifSensorDescription(
        key="operating_mode",
        report_name="heat_pump",
        params=PARAMS_TEXT,
    ),
    WebifSensorDescription(
        key="fault_message",
        report_name="heat_pump",
        params=PARAMS_TEXT,
    ),
    WebifSensorDescription(
        key="domestic_hot_water_temperature",
        report_name="heat_pump",
        params=PARAMS_TEMPERATURE,
    ),
    WebifSensorDescription(
        key="power_request",
        report_name="heat_pump",
        params=PARAMS_PERCENTAGE,
    ),
    WebifSensorDescription(
        key="target_temperature",
        report_name="heat_pump",
        params=PARAMS_TEMPERATURE,
    ),
    WebifSensorDescription(
        key="request",
        report_name="heat_pump",
        params=PARAMS_ENERGY,
    ),
    WebifSensorDescription(
        key="dynamic_switching_difference",
        report_name="heat_pump",
        params=PARAMS_KELVIN,
    ),
    WebifSensorDescription(
        key="flow_temperature",
        report_name="heat_pump",
        params=PARAMS_TEMPERATURE,
    ),
    WebifSensorDescription(
        key="return_temperature",
        report_name="heat_pump",
        params=PARAMS_TEMPERATURE,
    ),
    WebifSensorDescription(
        key="pump_m1_speed",
        report_name="heat_pump",
        params=PARAMS_PERCENTAGE,
    ),
    WebifSensorDescription(
        key="volume_flow",
        report_name="heat_pump",
        params=PARAMS_FLOW_RATE,
    ),
    WebifSensorDescription(
        key="diverter_valve_position",
        report_name="heat_pump",
        params=PARAMS_TEXT,
    ),
    WebifSensorDescription(
        key="wwp_sg_version",
        report_name="heat_pump",
        params=PARAMS_TEXT,
    ),
    WebifSensorDescription(
        key="wwp_ec_wbb_version",
        report_name="heat_pump",
        params=PARAMS_TEXT,
    ),
    WebifSensorDescription(
        key="target_power",
        report_name="heat_pump",
        params=PARAMS_POWER,
    ),
    WebifSensorDescription(
        key="actual_power",
        report_name="heat_pump",
        params=PARAMS_POWER,
    ),
    WebifSensorDescription(
        key="expansion_valve_outdoor_unit_inlet",
        report_name="heat_pump",
        params=PARAMS_TEMPERATURE,
    ),
    WebifSensorDescription(
        key="air_intake_temperature",
        report_name="heat_pump",
        params=PARAMS_TEMPERATURE,
    ),
    WebifSensorDescription(
        key="heat_exchanger_outdoor_unit_outlet_temperature",
        report_name="heat_pump",
        params=PARAMS_TEMPERATURE,
    ),
    WebifSensorDescription(
        key="compressor_suction_gas_temperature",
        report_name="heat_pump",
        params=PARAMS_TEMPERATURE,
    ),
    WebifSensorDescription(
        key="evi_suction_gas_temperature",
        report_name="heat_pump",
        params=PARAMS_TEMPERATURE,
    ),
    WebifSensorDescription(
        key="refrigerant_indoor_unit_outlet_temperature",
        report_name="heat_pump",
        params=PARAMS_TEMPERATURE,
    ),
    WebifSensorDescription(
        key="oil_sump_temperature",
        report_name="heat_pump",
        params=PARAMS_TEMPERATURE,
    ),
    WebifSensorDescription(
        key="discharge_gas_temperature",
        report_name="heat_pump",
        params=PARAMS_TEMPERATURE,
    ),
    WebifSensorDescription(
        key="low_pressure",
        report_name="heat_pump",
        params=PARAMS_PRESSURE,
    ),
    WebifSensorDescription(
        key="evaporation_temperature",
        report_name="heat_pump",
        params=PARAMS_TEMPERATURE,
    ),
    WebifSensorDescription(
        key="high_pressure",
        report_name="heat_pump",
        params=PARAMS_PRESSURE,
    ),
    WebifSensorDescription(
        key="condensation_temperature",
        report_name="heat_pump",
        params=PARAMS_TEMPERATURE,
    ),
    WebifSensorDescription(
        key="medium_pressure",
        report_name="heat_pump",
        params=PARAMS_PRESSURE,
    ),
    WebifSensorDescription(
        key="evi_saturation_temperature",
        report_name="heat_pump",
        params=PARAMS_TEMPERATURE,
    ),
    WebifSensorDescription(
        key="heating_superheat",
        report_name="heat_pump",
        params=PARAMS_KELVIN,
    ),
    WebifSensorDescription(
        key="heating_exv_opening",
        report_name="heat_pump",
        params=PARAMS_PERCENTAGE,
    ),
    WebifSensorDescription(
        key="compressor_superheat",
        report_name="heat_pump",
        params=PARAMS_KELVIN,
    ),
    WebifSensorDescription(
        key="cooling_exv_opening",
        report_name="heat_pump",
        params=PARAMS_PERCENTAGE,
    ),
    WebifSensorDescription(
        key="evi_superheat",
        report_name="heat_pump",
        params=PARAMS_KELVIN,
    ),
    WebifSensorDescription(
        key="evi_opening",
        report_name="heat_pump",
        params=PARAMS_PERCENTAGE,
    ),
    WebifSensorDescription(
        key="compressor_operating_hours",
        report_name="heat_pump",
        params=PARAMS_HOURS,
    ),
    WebifSensorDescription(
        key="compressor_switching_cycles",
        report_name="heat_pump",
        params=PARAMS_TEXT,
    ),
    WebifSensorDescription(
        key="defrost_switching_cycles",
        report_name="heat_pump",
        params=PARAMS_TEXT,
    ),
    WebifSensorDescription(
        key="compressor",
        report_name="heat_pump",
        params=PARAMS_RPM,
    ),
    WebifSensorDescription(
        key="outdoor_unit_variant",
        report_name="heat_pump",
        params=PARAMS_TEXT,
    ),
]
# One thing to check next: **`request` using `PARAMS_ENERGY` looks suspicious**. The WebIF value in your mock is `"4.3"`, and from the field name `Anforderung` it may represent a power/percentage/temperature-related demand rather than energy. I would verify that before finalizing the entity definitions.
