"""System Error enum of Weishaupt."""

from enum import IntEnum


class WhSystemError(IntEnum):
    """System Error enum of Weishaupt."""

    NO_ERROR = 65535

    REFRIGERANT_SENSOR_EXPANSION_VALVE_INLET = 1
    AIR_INTAKE_SENSOR = 2
    HEAT_EXCHANGER_SENSOR_OUTLET = 3
    COMPRESSOR_SUCTION_SENSOR = 4
    EVI_SUCTION_SENSOR = 5
    REFRIGERANT_SENSOR_INLET = 6
    OIL_SUMP_SENSOR = 7
    EVI_EXPANSION_VALVE = 8
    LOW_PRESSURE_SENSOR = 9
    HIGH_PRESSURE_SENSOR = 10
    MEDIUM_PRESSURE_SENSOR = 11
    COOLING_EXPANSION_VALVE_FAULT = 12
    INVERTER_COMMUNICATION = 13
    OUTDOOR_UNIT_COMMUNICATION = 14
    HIGH_PRESSURE_SWITCH = 15
    INVERTER_LOCKED = 16
    EEPROM_MEMORY_ERROR = 17
    CONTROLLER_TO_REFRIGERANT_UNIT_MODBUS_COMMUNICATION = 18
    HEAT_PUMP_SWITCHED_OFF_BY_INVERTER_ALARM = 19
    COMPRESSOR_CONFIGURATION_MISMATCH = 20
    LOW_PRESSURE_FAULT = 21
    LOW_SUPERHEAT = 22
    HIGH_SUPERHEAT = 23
    EVI_HIGH_SUPERHEAT = 24
    REFRIGERANT_LEVEL_TOO_LOW = 25
    HIGH_PRESSURE_FAULT = 26
    CONDENSATION_TEMPERATURE_TOO_LOW = 27
    CONDENSATION_TEMPERATURE_TOO_HIGH = 28
    EVAPORATION_TEMPERATURE_TOO_LOW = 29
    EVAPORATION_TEMPERATURE_TOO_HIGH = 30

    HEAT_PUMP_INCOMPATIBLE = 32
    CONTROLLER_TO_EM_HK_COMMUNICATION = 33

    FLOW_RATE_TOO_LOW = 40
    NEGATIVE_FLOW_TEMPERATURE_SPREAD = 41

    FAN_BLOCKED = 43
    FAN_SPEED_TOO_LOW = 44
    CONTROLLER_TO_REFRIGERANT_UNIT_COMMUNICATION_FAULT = 47

    OUTDOOR_SENSOR_INTERRUPTED = 50
    OUTDOOR_SENSOR_SHORT_CIRCUITED = 51
    HYDRAULIC_SWITCH_SENSOR_INTERRUPTED = 52
    HYDRAULIC_SWITCH_SENSOR_SHORT_CIRCUITED = 53
    DHW_SENSOR_INTERRUPTED = 54
    DHW_SENSOR_SHORT_CIRCUITED = 55
    CONDENSER_FLOW_SENSOR_INTERRUPTED = 56
    CONDENSER_FLOW_SENSOR_SHORT_CIRCUITED = 57
    FLOW_SENSOR_INTERRUPTED = 58
    FLOW_SENSOR_SHORT_CIRCUITED = 59
    RETURN_SENSOR_INTERRUPTED = 60
    RETURN_SENSOR_SHORT_CIRCUITED = 61

    BUFFER_SENSOR_INTERRUPTED = 64
    BUFFER_SENSOR_SHORT_CIRCUITED = 65
    REGENERATIVE_MIXER_SENSOR_INTERRUPTED = 66
    REGENERATIVE_MIXER_SENSOR_SHORT_CIRCUITED = 67

    SECOND_HEATING_CIRCUIT_FLOW_SENSOR_INTERRUPTED = 70
    SECOND_HEATING_CIRCUIT_FLOW_SENSOR_SHORT_CIRCUITED = 71

    SENSOR_T1_2_INTERRUPTED = 72
    SENSOR_T1_2_SHORT_CIRCUITED = 73
    SENSOR_T2_2_INTERRUPTED = 74
    SENSOR_T2_2_SHORT_CIRCUITED = 75

    ANALOG_INPUT_AE1_INTERRUPTED = 90
    ANALOG_INPUT_AE1_SHORT_CIRCUITED = 91
    ANALOG_INPUT_AE2_INTERRUPTED = 92
    ANALOG_INPUT_AE2_SHORT_CIRCUITED = 93
    ANALOG_INPUT_AE3_INTERRUPTED = 94
    ANALOG_INPUT_AE3_SHORT_CIRCUITED = 95

    HEAT_PUMP_OUTSIDE_OPERATING_LIMITS = 101
    MAXIMUM_DEFROST_TIME_EXCEEDED = 102
    REFRIGERANT_CIRCUIT_COMMUNICATION_FAULT = 103
    DISCHARGE_GAS_TEMPERATURE_TOO_HIGH = 104
    INVERTER_CURRENT_TOO_HIGH = 105
    CURRENT_CONSUMPTION_TOO_HIGH = 106
    INVERTER_DC_VOLTAGE_TOO_HIGH = 107
    INVERTER_DC_VOLTAGE_TOO_LOW = 108
    HEAT_PUMP_OUTSIDE_VOLTAGE_RANGE_LOW = 109
    HEAT_PUMP_OUTSIDE_VOLTAGE_RANGE_HIGH = 110
    HIGH_PRESSURE_SWITCH_2 = 111
    INVERTER_OVERHEATED = 112
    INVERTER_OVERHEATED_2 = 113
    COMPRESSOR_MOTOR_POSITION_UNDETERMINED = 114
    INVERTER_DC_VOLTAGE_TOO_LOW_2 = 117
    CURRENT_BETWEEN_INVERTER_AND_COMPRESSOR_TOO_HIGH = 118
    COMPRESSOR_CURRENT_TOO_HIGH_TIMEOUT = 119
    INVERTER_TEMPERATURE_TOO_HIGH = 120
    INVERTER_VOLTAGE_TOO_LOW = 121
    MODBUS_CONFIGURATION_ERROR = 122
    NO_MODBUS_CONNECTION = 123
    DISCHARGE_GAS_TEMPERATURE_TOO_HIGH_2 = 124
    INVERTER_TEMPERATURE_TOO_HIGH_2 = 127
    INVERTER_OVERHEATED_3 = 128
    MODBUS_COMMUNICATION_FAULT = 129
    MODBUS_COMMUNICATION_FAULT_2 = 130
    ELECTRONICS_FAULT = 133
    HIGH_PRESSURE_SWITCH_FAULT = 135
    COMPRESSOR_CONFIGURATION_MISMATCH_2 = 136
    HIGH_PRESSURE_SWITCH_CONFIGURATION_MISMATCH = 137
    DISCHARGE_GAS_TEMPERATURE_TOO_LOW = 140
    INVERTER_TEMPERATURE_TOO_LOW = 143
    CHOKE_COIL_TEMPERATURE_TOO_LOW = 144

    COMPRESSOR_CURRENT_SENSOR_PHASE_U_FAULT = 150
    COMPRESSOR_CURRENT_SENSOR_PHASE_V_FAULT = 151
    COMPRESSOR_CURRENT_SENSOR_PHASE_W_FAULT = 152
    CURRENT_SENSOR_FAULT = 153
    INVERTER_TEMPERATURE_SENSOR_FAULT = 154
    TEMPERATURE_SENSOR_FAULT = 155
    DISCHARGE_GAS_SENSOR_FAULT = 156
    NO_COMMUNICATION_WITH_REFRIGERANT_CONTROL_BOARD = 157
    EEPROM_MEMORY_ERROR_2 = 158
    CURRENT_CONSUMPTION_TOO_HIGH_2 = 159
    HEAT_PUMP_OUTSIDE_VOLTAGE_RANGE_2 = 160
    HEAT_PUMP_OUTSIDE_VOLTAGE_RANGE_3 = 161
    INVERTER_DC_VOLTAGE_TOO_HIGH_2 = 162
    INVERTER_DC_VOLTAGE_TOO_LOW_3 = 163
    HIGH_PRESSURE_SWITCH_3 = 164
    COMPRESSOR_PHASE_INTERRUPTED = 165
    INVERTER_OVERHEATED_4 = 166
    INVERTER_OVERHEATED_5 = 167
    COMPRESSOR_CONFIGURATION_ERROR = 168
    COMPRESSOR_CURRENT_TOO_HIGH = 169
    COMPRESSOR_PHASE_U_OVERVOLTAGE = 170
    COMPRESSOR_PHASE_V_OVERVOLTAGE = 171
    COMPRESSOR_PHASE_W_OVERVOLTAGE = 172
    COMPRESSOR_PHASE_FAILURE = 173
    COMPRESSOR_BLOCKED = 174
    COMPRESSOR_WILL_NOT_START = 175
    IRREGULAR_INVERTER_POWER_SUPPLY = 176
    COMPRESSOR_OVERLOADED = 177
    DISCHARGE_GAS_TEMPERATURE_TOO_HIGH_3 = 178
    INVERTER_TEMPERATURE = 179
    COMPRESSOR_BLOCKED_2 = 180
    COMPRESSOR_BLOCKED_3 = 181
    CURRENT_CONSUMPTION_TOO_HIGH_3 = 182
    CURRENT_CONSUMPTION_TOO_HIGH_4 = 183
    VOLTAGE_TOO_HIGH = 184
